### ISSUE TITLE
Compiling filetime in AIX fails

### ISSUE THREAD

**Issue by ayappanec** [alexcrichton/filetime#107]
Compiling filetime in AIX fails with below error.,
`rustc --crate-name filetime --edition=2018 /.cargo/registry/src/index.crates.io-d11c229612889eed/filetime-0.2.23/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=a98d88e96f31687d -C extra-filename=-a98d88e96f31687d --out-dir /tmp/pip-install-2doeq8db/tokenizers_a6dcd574fc864cb793f0985f2a16d7f5/target/release/deps -C strip=debuginfo -L dependency=/tmp/pip-install-2doeq8db/tokenizers_a6dcd574fc864cb793f0985f2a16d7f5/target/release/deps --extern cfg_if=/tmp/pip-install-2doeq8db/tokenizers_a6dcd574fc864cb793f0985f2a16d7f5/target/release/deps/libcfg_if-55e79adb7c27a106.rmeta --extern libc=/tmp/pip-install-2doeq8db/tokenizers_a6dcd574fc864cb793f0985f2a16d7f5/target/release/deps/liblibc-3a5102201a3aa852.rmeta --cap-lints allow -C link-arg=-bbigtoc -L/opt/freeware/lib -D_ALL_SOURCE -lpython3.9`

 ```
 error[E0308]: mismatched types
      --> /.cargo/registry/src/index.crates.io-d11c229612889eed/filetime-0.2.23/src/unix/utimensat.rs:58:55
       |
  58   |     let rc = unsafe { libc::utimensat(libc::AT_FDCWD, p.as_ptr(), times.as_ptr(), flags) };
       |                       ---------------                 ^^^^^^^^^^ expected `*const u8`, found `*const i8`
       |                       |
       |                       arguments to this function are incorrect
       |
       = note: expected raw pointer `*const u8`
                  found raw pointer `*const i8`
  note: function defined here
      --> /.cargo/registry/src/index.crates.io-d11c229612889eed/libc-0.2.154/src/unix/aix/mod.rs:3337:12
       |
  3337 |     pub fn utimensat(
       |            ^^^^^^^^^
```

**Comment by taiki-e** [comment]
Probably related to https://github.com/rust-lang/rust/pull/122986 and updating libc or compiler should fix it.

**Comment by ayappanec** [comment]
Closing it as per above comments
