### ISSUE TITLE
libc::lutimes not portable

### ISSUE THREAD

**Issue by bgermann** [alexcrichton/filetime#14]
With commit 5c2ceb13cff libc::lutimes was introduced. It is not very portable, which you can see at https://www.gnu.org/software/gnulib/manual/html_node/lutimes.html

As filetime is is a dependency for cargo, maybe this should be reworked.

**Comment by alexcrichton** [comment]
I had to [fix this on Android](https://github.com/alexcrichton/filetime/commit/9719f39529741794af65613f9d5c6eb3ef6b97ab) as well, and if you've got other platforms it needs to be fixed on PRs are more than welcome!

**Comment by bgermann** [comment]
Is it a valid fix to just error?

**Comment by bgermann** [comment]
Maybe #11 fixes this with the POSIX utimensat function.

**Comment by alexcrichton** [comment]
I just added a module which uses `utimensat`, but it may need more cfgs for more platforms.
