### ISSUE TITLE
filetime 0.1.14 issue on Solaris

### ISSUE THREAD

**Issue by psumbera** [alexcrichton/filetime#19]
I have tried to build Cargo 0.23 with filetime 0.1.14 (since the default version 0.1.12 expects lutimes() which is not available on Solaris). But I'm still getting following error (on Solaris). Note that with version 0.1.10 builds.

error[E0425]: cannot find value `utimensat` in module `libc`
 --> /scratch/userland-rust-s11.3/components/rust/cargo/build/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/filetime-0.1.14/src/unix/utimensat.rs:8:45
  |
8 |     super::utimensat(p, atime, mtime, libc::utimensat, 0)
  |                                             ^^^^^^^^^ did you mean `utimes`?
  |
help: possible candidate is found in another module, you can import it into scope
  |
1 | use imp::utimensat;
  |

error[E0425]: cannot find value `utimensat` in module `libc`
  --> /scratch/userland-rust-s11.3/components/rust/cargo/build/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/filetime-0.1.14/src/unix/utimensat.rs:12:45
   |
12 |     super::utimensat(p, atime, mtime, libc::utimensat, libc::AT_SYMLINK_NOFOLLOW)
   |                                             ^^^^^^^^^ did you mean `utimes`?
   |
help: possible candidate is found in another module, you can import it into scope
   |
1  | use imp::utimensat;
   |

error[E0425]: cannot find value `AT_SYMLINK_NOFOLLOW` in module `libc`
  --> /scratch/userland-rust-s11.3/components/rust/cargo/build/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/filetime-0.1.14/src/unix/utimensat.rs:12:62
   |
12 |     super::utimensat(p, atime, mtime, libc::utimensat, libc::AT_SYMLINK_NOFOLLOW)
   |                                                              ^^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `AT_FDCWD` in module `libc`
  --> /scratch/userland-rust-s11.3/components/rust/cargo/build/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/filetime-0.1.14/src/unix/mod.rs:64:17
   |
64 |         f(libc::AT_FDCWD, p.as_ptr() as *const _, times.as_ptr(), flags)
   |                 ^^^^^^^^ not found in `libc`

error: aborting due to 4 previous errors 

--

Any idea what could be possibly wrong?

**Comment by bgermann** [comment]
https://github.com/rust-lang/libc/commit/4a58331883ac84e7858c08665370c7ea56c26338 closes this issue.

**Comment by alexcrichton** [comment]
Yay!
