### ISSUE TITLE
#![feature(metadata_ext)] unstable

### ISSUE THREAD

**Issue by ivanceras** [alexcrichton/filetime#2]
This project is used in iron/staticfile,
but wasn't able to compile the examples sucessfully.

```
git clone https://github.com/iron/staticfile
cargo run --release --example router
```
```
filetime-0.1.2/src/lib.rs:1 #![feature(metadata_ext)]
                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~
```

$rustc -V
`rustc 1.1.0-beta (cd7d89af9 2015-05-16) (built 2015-05-16)`

**Comment by alexcrichton** [comment]
Unfortunately this is a limitation of this library, but hopefully these features will become stable in the 1.1 release!
