### ISSUE TITLE
libc::lutimes is not defined when building with --target=wasm32-unknown-emscripten

### ISSUE THREAD

**Issue by SSStormy** [alexcrichton/filetime#24]
I'm building a wasm project that depends on filetime and it looks like libc::lutimes is not defined for `wasm32-unknown-emscripten` targets.

Build log:
```
$ cargo web build --target=wasm32-unknown-emscripten
   Compiling filetime v0.1.15
error[E0425]: cannot find value `lutimes` in module `libc`
  --> /home/justas/.cargo/registry/src/github.com-1ecc6299db9ec823/filetime-0.1.15/src/unix/utimes.rs:12:42
   |
12 |     super::utimes(p, atime, mtime, libc::lutimes)
   |                                          ^^^^^^^ did you mean `utimes`?
error: aborting due to previous error
For more information about this error, try `rustc --explain E0425`.
error: Could not compile `filetime`.
error: build failed
```

This might just be an issue with libc so feel free to close it and I'll reopen it in the libc repo.

**Comment by alexcrichton** [comment]
Ah this is probably a case where the right API needs to be used for emscripten and the current fallback may be too aggressive or something like that. Unfortunately I'm not that famiar with emscripten though :(
