### ISSUE TITLE
Add functions for setting only mtime/atime

### ISSUE THREAD

**Issue by drrlvn** [alexcrichton/filetime#26]
Please add `set_file_mtime()` and `set_file_atime()` that set only one of the values.

In Linux this can be done by passing `UTIME_OMIT` as the argument that's not needed. See example in `libstdc++`'s implementation of `std::filesystem::last_write_time()`: https://github.com/gcc-mirror/gcc/blob/gcc-8_1_0-release/libstdc%2B%2B-v3/src/filesystem/std-ops.cc#L1067

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/filetime/pull/40
