### ISSUE TITLE
Fails to set Modified Time on FAT32 and exFAT

### ISSUE THREAD

**Issue by khionu** [alexcrichton/filetime#30]
I have been debugging an issue with [Cargo validating the crate as a tarball](https://users.rust-lang.org/t/cargo-package-failure-validating-tarball/21455) and I had traced it to being invalid arguments being sent to Windows. I was recommended to try moving the project to my main drive on a whim, and surprisingly that fixed my issue. After some testing, I found that, of FAT32, exFAT, and NTFS, only NTFS worked while on the NT Kernel.

**Comment by memoryruins** [comment]
The error from ``cargo package``  in the linked thread also occurs on linux with an exFAT usb drive.
```
error: failed to verify package tarball

Caused by:
  failed to unpack `/home/michael/usb-exfat/evac/target/package/evac-0.1.0/Cargo.toml.orig`
```
I was unable to test a FAT32 drive at this time
```
rustc: 1.31.0-nightly (155510e37 2018-10-20)
OS: Arch Linux x86_64
Kernel: 4.14.76-1-lts
```

**Comment by alexcrichton** [comment]
Thanks for the report! I'm not sure that we want to fix this in this crate though because the error here is legitimate. The error happens in `tar` and is propagated [here](https://github.com/alexcrichton/tar-rs/blob/7660b4f7172630c6bfa194d9b4e66caee27d1dae/src/entry.rs#L533-L535), but specifically in Cargo we're ok ignoring these sorts of errors. Perhaps a feature could be added to `tar` to optionally ignore the errors an then Cargo could turn that on by default?

**Comment by khionu** [comment]
> error here is legitimate.

Legitimate? How is it legitimate in such a way where it shouldn't be compensated for? Is this crate not responsible for the arguments that are being called invalid? I'm not used to working with components this low-level, and while I do see that this is something that should be handled out of the scope of this crate, the fact that there is different behavior for FAT-derived FS's and NTFS/extN FS's is an issue I would imagine needs to be handled somewhere...

Assuming you're correct in your assessment, I would agree that that's the best course of action.

**Comment by alexcrichton** [comment]
Er sorry by legitimate it looks like the filesystem simply doesn't support changing mtimes. I don't think the arguments to the syscall are invalid, it's just not possible to do this operation.

**Comment by khionu** [comment]
Ahh... then, yes, I would agree with your course of action.

I'll open the issues where appropriate.
