### ISSUE TITLE
Parsing fails due to new "Edition" field

### ISSUE THREAD

**Issue by gDelgado14** [alexcrichton/filetime#41]
Hello,

Looks like the following commit prevents us from compiling cargo-watch on stable, since it adds a new field, that cannot be parsed on stable.

https://github.com/alexcrichton/filetime/commit/38857bbda347a983a4b9b252e22e48cbd3f5443c

Here's a screenshot. 

![image](https://user-images.githubusercontent.com/10621548/57957241-a2681300-78c9-11e9-8610-c0ca2f660d39.png)

Any suggestions on how to fix this issue without us having to go over to nightly?

**Comment by alexcrichton** [comment]
Thanks for the report! This crate now requires rustc 1.32.0+, so you'll want to update your rustc.
