### ISSUE TITLE
Can not set times before 1970

### ISSUE THREAD

**Issue by unbounded** [alexcrichton/filetime#6]
FileTime uses u64 for the seconds field, rendering it unable to represent timestamps before 1970.
I believe time_t is signed on most systems, so using an i64 would be a better match.

**Comment by alexcrichton** [comment]
Thanks for the report! Definitely sounds like a bug.

I'd like to keep backwards compatibility for now so we can likely just add a suite of mirroring APIs that work with `i64` instead of `u64`, and then we could also add notes to the documentation of other APIs and such about this.

**Comment by alexcrichton** [comment]
I think this has since been fixed, so closing.
