### ISSUE TITLE
Why is `11644473600` second subtracted in the `unix_second` fuction  calculation?

### ISSUE THREAD

**Issue by muwuren** [alexcrichton/filetime#76]
In the `unix_seconds()` function of the struct `FileTime`, it is calculated unix timestamp for 1970 year.
When the system is `Windows`, the time difference from 1961 to 1970 needs to be subtracted. This value may be `3287 * 24 * 3600 = 283996800`, not be `11644473600` ?

**Comment by alexcrichton** [comment]
I don't know myself at this point (it's been many years since I wrote this crate) and I probably ended up copying it from somewhere else. Is the crate producing the wrong results for you?

**Comment by muwuren** [comment]
Sorry, I have just tested on windows and Linux platforms and found that the value of `11644473600` is correct. Perhaps the starting point of timestamp under Windows does not start in 1961.
